### ISSUE TITLE
How to sync permissions to live

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/RoleManager#3]
I saw with great interest that you have added the possibility to sync permissions from one environment to another, any chance you could explain how you create the config files or provide an example?

**Comment by aocneanu** [comment]
Did you get a change to read the Changelog for v2.8.8?

**Comment by stevefrost** [comment]
Yes, I was unclear on this part
"after generating each config file"

**Comment by stevefrost** [comment]
Ah, this wouldn't run for me 'php artisan enso:roles:add-missing-permission' I guess they add the permission for those buttons?

**Comment by aocneanu** [comment]
If you have the time make a PR where you take the missing command from v2.3.43 and add it again. I removed a lot of old commands but by mistake I removed this as well.
