### ISSUE TITLE
Multiple roles for a user

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/RoleManager#5]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Allow users to be assigned multiple roles

Currently there is a 1 to 1 relationship with users and roles, I think it would benefit from allowing a hasMany relationship. My current example is this

I have three roles (staff/Manager/Superuser)
Staff cannot add new users, that permission is only available to managers or superusers, however I have a "staff" level user that needs to be able to add new users without gaining any other permissions, currently the only possible solution would be to create another role which clones the "staff" role, but adds the permission for creating users, what would be a better solution would be to add a new role which includes the create user permission and assign that to the user, so that they have two roles.

Does that make sense?

**Comment by aocneanu** [comment]
>what would be a better solution would be to add a new role which includes the create user permission and assign that to the user, so that they have two roles.

Yes, would be better in a context of three users with 4 roles.

We discussed about this over and over again and this is something that we are definitely not going to do, the current implementation being at the core philosophy of Enso. But If it really makes sense for your case you can make a fork and add the functionality yourself, I will help you with indicating all the "points" that need to be touched.

Enso is meant for business applications. We see roles as positions in a company. We want a role for each position.

Is one is looking for an admin panel for a website or a CMS, there are far more straightforward options. 

The current Owner-User-Role-Permission structure is designed to handle tens of roles with thousands permissions for thousands of users, from a friendly interface, with auto syncing between dev and live instances.

Thought exercise:

Imagine having tens of positions in a company, each position needing a specific collection of 5-6 roles from a total of maybe 30-40 roles. Imagine configuring by hand for each user the specific collection of 5-6 roles. Estimated time of completion : Probably Never

Two months later, you further develop the app and add 100 more permissions. Imagine splitting the permissions per existing roles, where you will have to analyse each role collection configuration to be sure that nobody gets the permission they are not supposed to. An alternative would be creating new roles with only the 100 permissions, and then adding by hand the appropriate roles to the x000 users.
Estimated time of completion for either of the alternatives : Probably Never

**Comment by aocneanu** [comment]
@stevefrost I will close this for now, if you want me to elaborate more on this subject you can reopen it.
