### ISSUE TITLE
Configuring roles not working

### ISSUE THREAD

**Issue by vmcvlad** [laravel-enso/RoleManager#6]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After upgrading to Enso 2.14.0, configuring roles is no longer possible from the interface.

### Steps to Reproduce

1. Try to configure any role

### Expected behavior

The role's permissions should load inside the content manager component in order to be configured.

### Actual behavior

A tostr error message is presented, and the following error can be observed in the browser's console.
![image](https://user-images.githubusercontent.com/37445394/51305507-bc8d0400-1a43-11e9-802d-bc3063168c98.png)

**Comment by aocneanu** [comment]
fixed with 60708ebcfca1bb1bbe22342e653f6aeb83f64ba6
